
/* PERMISSIONS */
GRANT CONNECT TO "";
GRANT RESOURCE TO "USER_1";
GRANT SELECT_CATALOG_ROLE TO "_USR_NAME_";
GRANT DEBUG CONNECT SESSION TO "_USR_NAME_";
GRANT UNLIMITED TABLESPACE TO "_USR_NAME_";
ALTER USER _USR_NAME_ QUOTA UNLIMITED ON "_TABLESPACE_NAME_";

/* CREATE USER */
CREATE USER _USR_NAME_ IDENTIFIED BY "SET_USER_PASSWORD_HERE"
  DEFAULT TABLESPACE _TABLESPACE_NAME_
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  QUOTA UNLIMITED ON _TABLESPACE_NAME_;

/* CREATE TABLESPACE */
CREATE SMALLFILE TABLESPACE _TABLESPACE_NAME_
  DATAFILE SIZE 100M
  AUTOEXTEND ON NEXT 50M
  MAXSIZE 30G
  LOGGING EXTENT MANAGEMENT LOCAL SEGMENT
  SPACE MANAGEMENT AUTO;

/* EXTEND TABLESPACE */
ALTER TABLESPACE _TABLESPACE_NAME_
  ADD DATAFILE SIZE 100M
  AUTOEXTEND ON NEXT 50M
  MAXSIZE 30G;